/**
 * SPDX-FileCopyrightText: (c) 2023 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.training.formExercise.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Form service. Represents a row in the &quot;MY_Form&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.formExercise.model.impl.FormModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.formExercise.model.impl.FormImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Form
 * @generated
 */
@ProviderType
public interface FormModel extends BaseModel<Form>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form model instance should use the {@link Form} interface instead.
	 */

	/**
	 * Returns the primary key of this form.
	 *
	 * @return the primary key of this form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form.
	 *
	 * @param primaryKey the primary key of this form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group ID of this form.
	 *
	 * @return the group ID of this form
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this form.
	 *
	 * @param groupId the group ID of this form
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the form ID of this form.
	 *
	 * @return the form ID of this form
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this form.
	 *
	 * @param formId the form ID of this form
	 */
	public void setFormId(long formId);

	/**
	 * Returns the company ID of this form.
	 *
	 * @return the company ID of this form
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this form.
	 *
	 * @param companyId the company ID of this form
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this form.
	 *
	 * @return the user ID of this form
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this form.
	 *
	 * @param userId the user ID of this form
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this form.
	 *
	 * @return the user uuid of this form
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this form.
	 *
	 * @param userUuid the user uuid of this form
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this form.
	 *
	 * @return the user name of this form
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this form.
	 *
	 * @param userName the user name of this form
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this form.
	 *
	 * @return the create date of this form
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this form.
	 *
	 * @param createDate the create date of this form
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this form.
	 *
	 * @return the modified date of this form
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this form.
	 *
	 * @param modifiedDate the modified date of this form
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the address of this form.
	 *
	 * @return the address of this form
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this form.
	 *
	 * @param address the address of this form
	 */
	public void setAddress(String address);

	/**
	 * Returns the city of this form.
	 *
	 * @return the city of this form
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this form.
	 *
	 * @param city the city of this form
	 */
	public void setCity(String city);

	/**
	 * Returns the comment of this form.
	 *
	 * @return the comment of this form
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this form.
	 *
	 * @param comment the comment of this form
	 */
	public void setComment(String comment);

	/**
	 * Returns the email of this form.
	 *
	 * @return the email of this form
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this form.
	 *
	 * @param email the email of this form
	 */
	public void setEmail(String email);

	/**
	 * Returns the name of this form.
	 *
	 * @return the name of this form
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this form.
	 *
	 * @param name the name of this form
	 */
	public void setName(String name);

	/**
	 * Returns the province of this form.
	 *
	 * @return the province of this form
	 */
	@AutoEscape
	public String getProvince();

	/**
	 * Sets the province of this form.
	 *
	 * @param province the province of this form
	 */
	public void setProvince(String province);

	/**
	 * Returns the state of this form.
	 *
	 * @return the state of this form
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this form.
	 *
	 * @param state the state of this form
	 */
	public void setState(String state);

	/**
	 * Returns the sum of this form.
	 *
	 * @return the sum of this form
	 */
	public int getSum();

	/**
	 * Sets the sum of this form.
	 *
	 * @param sum the sum of this form
	 */
	public void setSum(int sum);

	/**
	 * Returns the surname of this form.
	 *
	 * @return the surname of this form
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this form.
	 *
	 * @param surname the surname of this form
	 */
	public void setSurname(String surname);

	/**
	 * Returns the val1 of this form.
	 *
	 * @return the val1 of this form
	 */
	public int getVal1();

	/**
	 * Sets the val1 of this form.
	 *
	 * @param val1 the val1 of this form
	 */
	public void setVal1(int val1);

	/**
	 * Returns the val2 of this form.
	 *
	 * @return the val2 of this form
	 */
	public int getVal2();

	/**
	 * Sets the val2 of this form.
	 *
	 * @param val2 the val2 of this form
	 */
	public void setVal2(int val2);

	@Override
	public Form cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}